// src/routes/ModulesTab.svelte
<script lang="ts">
  import { store } from '../lib/store.svelte';
  import { ICONS } from '../lib/constants';
  import { onMount } from 'svelte';
  import { slide } from 'svelte/transition';
  import Skeleton from '../components/Skeleton.svelte';
  import BottomActions from '../components/BottomActions.svelte';
  import { API } from '../lib/api';
  import type { Module, MountMode } from '../lib/types';
  import './ModulesTab.css';
  let searchQuery = $state('');
  let filterType = $state('all');
  let showUnmounted = $state(false); 
  let expandedId = $state<string | null>(null);
  let initialRulesSnapshot = $state<Record<string, string>>({});
  onMount(() => {
    load();
  });
  function load() {
    store.loadModules().then(() => {
        const snapshot: Record<string, string> = {};
        store.modules.forEach(m => {
            snapshot[m.id] = JSON.stringify(m.rules);
        });
        initialRulesSnapshot = snapshot;
    });
  }
  let dirtyModules = $derived(store.modules.filter(m => {
      const initial = initialRulesSnapshot[m.id];
      if (!initial) return false;
      return JSON.stringify(m.rules) !== initial;
  }));
  let isDirty = $derived(dirtyModules.length > 0);
  async function save() {
    store.saving.modules = true;
    try {
        for (const mod of dirtyModules) {
            await API.saveModuleRules(mod.id, mod.rules);
        }
        await load();
        store.showToast(store.L.modules?.saveSuccess || store.L.common?.saveSuccess || "Saved successfully", 'success');
    } catch (e: any) {
        console.error(e);
        store.showToast(e.message || store.L.modules?.saveFailed || "Failed to save", 'error');
    } finally {
        store.saving.modules = false;
    }
  }
  let filteredModules = $derived(store.modules.filter(m => {
    const q = searchQuery.toLowerCase();
    const matchSearch = m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q);
    const matchFilter = filterType === 'all' || m.mode === filterType;
    const matchMounted = showUnmounted || m.is_mounted;
    return matchSearch && matchFilter && matchMounted;
  }));
  function toggleExpand(id: string) {
    expandedId = expandedId === id ? null : id;
  }
  function handleKeydown(e: KeyboardEvent, id: string) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      toggleExpand(id);
    }
  }
  function getModeLabel(mod: Module) {
      const m = store.L.modules?.modes;
      if (!mod.is_mounted) return m?.none ?? 'None';
      const mode = mod.rules.default_mode;
      if (mode === 'magic') return m?.magic ?? 'Magic Mount';
      if (mode === 'hymofs') return m?.hymo ?? 'HymoFS';
      if (mode === 'ignore') return m?.ignore ?? 'Ignore';
      return m?.auto ?? 'OverlayFS';
  }
  function addPathRule(mod: Module) {
      if (!mod.rules.paths) mod.rules.paths = {};
      let newKey = "new/path";
      let counter = 1;
      while (newKey in mod.rules.paths) {
          newKey = `new/path${counter++}`;
      }
      mod.rules.paths[newKey] = 'magic';
      mod.rules = { ...mod.rules };
  }
  function removePathRule(mod: Module, path: string) {
      delete mod.rules.paths[path];
      mod.rules = { ...mod.rules };
  }
  function updatePathKey(mod: Module, oldPath: string, newPath: string) {
      if (oldPath === newPath) return;
      if (!newPath.trim()) return;
      const mode = mod.rules.paths[oldPath];
      delete mod.rules.paths[oldPath];
      mod.rules.paths[newPath] = mode;
      mod.rules = { ...mod.rules };
  }
  function updatePathMode(mod: Module, path: string, mode: MountMode) {
      mod.rules.paths[path] = mode;
      mod.rules = { ...mod.rules };
  }
</script>
<div class="md3-card desc-card">
  <p class="desc-text">
    {store.L.modules?.desc}
  </p>
</div>
<div class="search-container">
  <svg class="search-icon" viewBox="0 0 24 24"><path d={ICONS.search} /></svg>
  <input 
    type="text" 
    class="search-input" 
    placeholder={store.L.modules?.searchPlaceholder}
    bind:value={searchQuery}
  />
  <div class="filter-controls">
    <div class="checkbox-wrapper">
        <input type="checkbox" id="show-unmounted" bind:checked={showUnmounted} />
        <label for="show-unmounted" title="Show unmounted modules">{store.L.modules?.filterAll ?? 'All'}</label>
    </div>
    <div class="vertical-divider"></div>
    <span class="filter-label-text">{store.L.modules?.filterLabel}</span>
    <select class="filter-select" bind:value={filterType}>
      <option value="all">{store.L.modules?.filterAll}</option>
      <option value="auto">{store.L.modules?.modeAuto}</option>
      <option value="magic">{store.L.modules?.modeMagic}</option>
      {#if store.storage?.hymofs_available}
         <option value="hymofs">HymoFS</option>
      {/if}
    </select>
  </div>
</div>
{#if store.loading.modules}
  <div class="rules-list">
    {#each Array(5) as _}
      <div class="rule-card">
        <div class="rule-info">
          <div class="skeleton-group">
            <Skeleton width="60%" height="20px" />
            <Skeleton width="40%" height="14px" />
          </div>
        </div>
        <Skeleton width="120px" height="40px" borderRadius="4px" />
      </div>
    {/each}
  </div>
{:else if filteredModules.length === 0}
  <div class="empty-state">
    {store.modules.length === 0 ?
      (store.L.modules?.empty ?? "No enabled modules found") : 
      "No matching modules"}
  </div>
{:else}
  <div class="rules-list">
    {#each filteredModules as mod (mod.id)}
      <div 
        class="rule-card" 
        class:expanded={expandedId === mod.id} 
        class:dirty={initialRulesSnapshot[mod.id] !== JSON.stringify(mod.rules)}
        class:unmounted={!mod.is_mounted}
      >
        <div 
            class="rule-main"
            onclick={() => toggleExpand(mod.id)}
            onkeydown={(e) => handleKeydown(e, mod.id)}
            role="button"
            tabindex="0"
        >
          <div class="rule-info">
            <div class="info-col">
              <span class="module-name">{mod.name}</span>
              <span class="module-id">{mod.id} <span class="version-tag">{mod.version}</span></span>
            </div>
          </div>
          <div class="mode-badge {
               !mod.is_mounted ? 'badge-none' :
               mod.rules.default_mode === 'magic' ? 'badge-magic' : 
               mod.rules.default_mode === 'hymofs' ? 'badge-hymofs' : 
               'badge-auto'}"
               style:background-color={
                 !mod.is_mounted ? '' :
                 mod.rules.default_mode === 'hymofs' ? 'var(--md-sys-color-primary-container)' : ''
               }
               style:color={
                 !mod.is_mounted ? '' :
                 mod.rules.default_mode === 'hymofs' ? 'var(--md-sys-color-on-primary-container)' : ''
               }>
            {getModeLabel(mod)}
          </div>
        </div>
        {#if expandedId === mod.id}
          <div class="rule-details" transition:slide={{ duration: 200 }}>
            <p class="module-desc">{mod.description ||
              (store.L.modules?.noDesc ?? 'No description')}</p>
            <p class="module-meta">{store.L.modules?.author ??
              'Author'}: {mod.author || (store.L.modules?.unknown ?? 'Unknown')}</p>
            {#if !mod.is_mounted}
                <div class="status-alert">
                    <svg viewBox="0 0 24 24" width="16" height="16"><path d={ICONS.info} fill="currentColor"/></svg>
                    <span>This module is currently not mounted.</span>
                </div>
            {/if}
            <div class="config-section">
              <div class="config-row">
                <span class="config-label">{store.L.modules?.defaultMode ??
                  'Default Strategy'}:</span>
                <div class="text-field compact-select">
                  <select 
                    bind:value={mod.rules.default_mode}
                    onclick={(e) => e.stopPropagation()}
                  >
                    <option value="overlay">{store.L.modules?.modes?.auto ??
                      'OverlayFS (Auto)'}</option>
                    <option value="magic">{store.L.modules?.modes?.magic ??
                      'Magic Mount'}</option>
                    {#if store.storage?.hymofs_available}
                      <option value="hymofs">{store.L.modules?.modes?.hymo ??
                        'HymoFS'}</option>
                    {/if}
                    <option value="ignore">{store.L.modules?.modes?.ignore ??
                      'Disable (Ignore)'}</option>
                  </select>
                </div>
              </div>
              <div class="paths-editor">
                 <div class="paths-header">
                     <span class="config-label">{store.L.modules?.pathRules ?? 'Path Overrides'}:</span>
                     <button class="btn-icon add-rule" onclick={() => addPathRule(mod)} title={store.L.modules?.addRule ??
                         'Add Rule'}>
                         <svg viewBox="0 0 24 24" width="20" height="20"><path d={ICONS.add} fill="currentColor"/></svg>
                     </button>
                 </div>
                  {#if mod.rules.paths && Object.keys(mod.rules.paths).length > 0}
                    <div class="path-list">
                        {#each Object.entries(mod.rules.paths) as [path, mode]}
                            <div class="path-row">
                                <input 
                                    type="text" 
                                    class="path-input" 
                                    value={path} 
                                    onchange={(e) => updatePathKey(mod, path, e.currentTarget.value)}
                                    placeholder={store.L.modules?.placeholder ??
                                    "e.g. system/fonts"}
                                />
                                <select 
                                    class="path-mode-select"
                                    value={mode}
                                    onchange={(e) => updatePathMode(mod, path, e.currentTarget.value as MountMode)}
                                >
                                    <option value="overlay">{store.L.modules?.modes?.short?.auto ??
                                      'Overlay'}</option>
                                    <option value="magic">{store.L.modules?.modes?.short?.magic ??
                                      'Magic'}</option>
                                    {#if store.storage?.hymofs_available}
                                        <option value="hymofs">{store.L.modules?.modes?.short?.hymo ??
                                          'HymoFS'}</option>
                                    {/if}
                                    <option value="ignore">{store.L.modules?.modes?.short?.ignore ??
                                      'Ignore'}</option>
                                </select>
                                <button class="btn-icon delete" onclick={() => removePathRule(mod, path)} title="Remove rule">
                                     <svg viewBox="0 0 24 24" width="18" height="18"><path d={ICONS.delete} fill="currentColor"/></svg>
                                </button>
                            </div>
                        {/each}
                    </div>
                 {:else}
                    <div class="empty-paths">{store.L.modules?.noRules ??
                      'No path overrides defined.'}</div>
                 {/if}
              </div>
            </div>
          </div>
        {/if}
      </div>
    {/each}
  </div>
{/if}
<BottomActions>
  <button class="btn-tonal" onclick={load} disabled={store.loading.modules} title={store.L.modules?.reload}>
    <svg viewBox="0 0 24 24" width="20" height="20"><path d={ICONS.refresh} fill="currentColor"/></svg>
  </button>
  <div class="spacer"></div>
  <button class="btn-filled" onclick={save} disabled={store.saving.modules || !isDirty}>
    <svg viewBox="0 0 24 24" width="18" height="18"><path d={ICONS.save} fill="currentColor"/></svg>
    {store.saving.modules ?
      store.L.common?.saving : store.L.modules?.save}
  </button>
</BottomActions>

// src/routes/ModulesTab.tsx
/**
 * Copyright 2026 Hybrid Mount Authors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { createSignal, createMemo, onMount, Show, For } from "solid-js";
import { store } from "../lib/store";
import { ICONS } from "../lib/constants";
import Skeleton from "../components/Skeleton";
import BottomActions from "../components/BottomActions";
import { API } from "../lib/api";
import type { Module, MountMode } from "../lib/types";
import "./ModulesTab.css";
import "@material/web/iconbutton/filled-tonal-icon-button.js";
import "@material/web/button/filled-button.js";
import "@material/web/icon/icon.js";

export default function ModulesTab() {
  const [searchQuery, setSearchQuery] = createSignal("");
  const [filterType, setFilterType] = createSignal("all");
  const [showUnmounted, setShowUnmounted] = createSignal(false); // 默认不显示未挂载
  const [expandedId, setExpandedId] = createSignal<string | null>(null);
  const [initialRulesSnapshot, setInitialRulesSnapshot] = createSignal<
    Record<string, string>
  >({});
  const [isSaving, setIsSaving] = createSignal(false);

  onMount(() => {
    load();
  });

  function load() {
    store.loadModules().then(() => {
      const snapshot: Record<string, string> = {};
      store.modules.forEach((m) => {
        snapshot[m.id] = JSON.stringify(m.rules);
      });
      setInitialRulesSnapshot(snapshot);
    });
  }

  const dirtyModules = createMemo(() =>
    store.modules.filter((m) => {
      const initial = initialRulesSnapshot()[m.id];
      if (!initial) return false;
      return JSON.stringify(m.rules) !== initial;
    }),
  );

  const isDirty = createMemo(() => dirtyModules().length > 0);

  function updateModule(modId: string, transform: (m: Module) => Module) {
    const idx = store.modules.findIndex((m) => m.id === modId);
    if (idx === -1) return;

    const newModules = [...store.modules];
    newModules[idx] = transform({ ...newModules[idx] });
    store.modules = newModules;
  }

  async function performSave() {
    setIsSaving(true);
    try {
      const dirty = dirtyModules();
      for (const mod of dirty) {
        await API.saveModuleRules(mod.id, mod.rules);
      }
      await load();
      store.showToast(
        store.L.modules?.saveSuccess || "Saved successfully",
        "success",
      );
    } catch (e: any) {
      store.showToast(e.message || "Failed to save", "error");
    } finally {
      setIsSaving(false);
    }
  }

  const filteredModules = createMemo(() =>
    store.modules.filter((m) => {
      const q = searchQuery().toLowerCase();
      if (!m.is_mounted && !showUnmounted()) {
        return false;
      }
      const matchSearch =
        m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q);
      if (!matchSearch) return false;
      if (filterType() !== "all" && m.mode !== filterType()) {
        return false;
      }

      return true;
    }),
  );

  function toggleExpand(id: string) {
    if (expandedId() === id) {
      setExpandedId(null);
    } else {
      setExpandedId(id);
    }
  }

  function getModeLabel(mod: Module) {
    const m = store.L.modules?.modes;
    if (!mod.is_mounted) return m?.none ?? "Unmounted";
    if (mod.mode === "magic") return m?.magic ?? "Magic";
    return m?.auto ?? "Overlay";
  }

  function getModeClass(mod: Module) {
    if (!mod.is_mounted) return "mode-ignore";
    if (mod.mode === "magic") return "mode-magic";
    return "mode-auto";
  }

  function updateModuleRules(
    modId: string,
    updateFn: (rules: Module["rules"]) => Module["rules"],
  ) {
    updateModule(modId, (m) => ({ ...m, rules: updateFn(m.rules) }));
  }

  function updateDefaultMode(mod: Module, mode: MountMode) {
    updateModuleRules(mod.id, (rules) => ({ ...rules, default_mode: mode }));
  }

  return (
    <>
      <div class="modules-page">
        <div class="header-section">
          <div class="search-bar">
            <svg class="search-icon" viewBox="0 0 24 24">
              <path d={ICONS.search} />
            </svg>
            <input
              type="text"
              class="search-input"
              placeholder={store.L.modules?.searchPlaceholder}
              aria-label={
                store.L.modules?.searchPlaceholder || "Search modules"
              }
              value={searchQuery()}
              onInput={(e) => setSearchQuery(e.currentTarget.value)}
            />

            <div class="filter-group">
              <button
                class="btn-icon"
                onClick={() => setShowUnmounted(!showUnmounted())}
                title={showUnmounted() ? "Hide unmounted" : "Show unmounted"}
                style={{
                  color: showUnmounted()
                    ? "var(--md-sys-color-primary)"
                    : "var(--md-sys-color-outline)",
                }}
              >
                <svg viewBox="0 0 24 24" width="20" height="20">
                  <path
                    d={
                      showUnmounted() ? ICONS.visibility : ICONS.visibility_off
                    }
                    fill="currentColor"
                  />
                </svg>
              </button>

              <select
                class="filter-select"
                value={filterType()}
                onChange={(e) => setFilterType(e.currentTarget.value)}
                aria-label={store.L.modules?.filterLabel || "Filter modules"}
                title={store.L.modules?.filterLabel || "Filter modules"}
              >
                <option value="all">{store.L.modules?.filterAll}</option>
                <option value="auto">Overlay</option>
                <option value="magic">Magic</option>
              </select>
            </div>
          </div>
        </div>

        <div class="modules-list">
          <Show
            when={!store.loading.modules}
            fallback={
              <For each={Array(6)}>
                {() => <Skeleton height="64px" borderRadius="16px" />}
              </For>
            }
          >
            <Show
              when={filteredModules().length > 0}
              fallback={
                <div class="empty-state">
                  <div>No modules found.</div>
                  <Show when={!showUnmounted()}>
                    <div
                      style={{
                        "font-size": "12px",
                        opacity: "0.7",
                        "margin-top": "8px",
                      }}
                    >
                      Unmounted modules are hidden.
                    </div>
                  </Show>
                </div>
              }
            >
              <For each={filteredModules()}>
                {(mod) => (
                  <div
                    class={`module-card ${expandedId() === mod.id ? "expanded" : ""} ${initialRulesSnapshot()[mod.id] !== JSON.stringify(mod.rules) ? "dirty" : ""}`}
                  >
                    <div
                      class="module-header"
                      onClick={() => toggleExpand(mod.id)}
                      role="button"
                      tabIndex={0}
                      onKeyDown={(e) =>
                        e.key === "Enter" && toggleExpand(mod.id)
                      }
                    >
                      <div class="module-info">
                        <div class="module-name">{mod.name}</div>
                        <div class="module-meta">
                          <span class="module-id">{mod.id}</span>
                          <span class="version-badge">{mod.version}</span>
                        </div>
                      </div>
                      <div class={`mode-indicator ${getModeClass(mod)}`}>
                        {getModeLabel(mod)}
                      </div>
                    </div>

                    <div class="module-body-wrapper">
                      <div class="module-body-inner">
                        <div class="module-body-content">
                          <p class="module-desc">{mod.description}</p>

                          <div class="body-section">
                            <div class="section-label">
                              {store.L.modules?.defaultMode ?? "Strategy"}
                            </div>
                            <div class="strategy-selector">
                              <button
                                class={`strategy-option ${mod.rules.default_mode === "overlay" ? "selected" : ""}`}
                                onClick={() =>
                                  updateDefaultMode(mod, "overlay")
                                }
                              >
                                <span class="opt-title">
                                  {store.L.modules?.modes?.short?.auto ??
                                    "Overlay"}
                                </span>
                                <span class="opt-sub">Default</span>
                              </button>
                              <button
                                class={`strategy-option ${mod.rules.default_mode === "magic" ? "selected" : ""}`}
                                onClick={() => updateDefaultMode(mod, "magic")}
                              >
                                <span class="opt-title">
                                  {store.L.modules?.modes?.short?.magic ??
                                    "Magic"}
                                </span>
                                <span class="opt-sub">Compat</span>
                              </button>
                              <button
                                class={`strategy-option ${mod.rules.default_mode === "ignore" ? "selected" : ""}`}
                                onClick={() => updateDefaultMode(mod, "ignore")}
                              >
                                <span class="opt-title">
                                  {store.L.modules?.modes?.short?.ignore ??
                                    "Ignore"}
                                </span>
                                <span class="opt-sub">Disable</span>
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </For>
            </Show>
          </Show>
        </div>
      </div>

      <BottomActions>
        <md-filled-tonal-icon-button
          onClick={load}
          disabled={store.loading.modules}
          title={store.L.modules?.reload}
        >
          <md-icon>
            <svg viewBox="0 0 24 24">
              <path d={ICONS.refresh} />
            </svg>
          </md-icon>
        </md-filled-tonal-icon-button>

        <div class="spacer"></div>

        <md-filled-button
          onClick={performSave}
          disabled={isSaving() || !isDirty()}
        >
          <md-icon slot="icon">
            <svg viewBox="0 0 24 24">
              <path d={ICONS.save} />
            </svg>
          </md-icon>
          {isSaving() ? store.L.common?.saving : store.L.modules?.save}
        </md-filled-button>
      </BottomActions>
    </>
  );
}
